### PR TITLE
Move Secure Git Guide to SvelteKit

### PR DESCRIPTION
**Pull request by grmbyrn**
[Issue #68](https://github.com/nautilus-cyberneering/secure-git-guide/issues/68) 

Remove the old version. Make secure-git-guide-branch the root folder. Update README with info on how to run SvelteKit. Replace old version of linters and gitignore with secure-git-guide-branch's.

### CODE REVIEW

**Comment by josecelano** [comment]
Hi @grmbyrn I think we should:

- Add the folder `site` to `.gitignore`.
- Remove the current MegaLinter configuration: `.mega-linter.yml`, ...
- Remove mkdocs configuration: `mkdocs.yml`
- Remove both workflows: `deploy-documentation.yml`  and `mega-linter.yml`

I think the repo should contain only:

- The new version you did.
- Updated README

I mean, since we are going to install MegaLinter from scratch we should not add any config now. And we have to remove the deploy workflow because we are not using mkdocs anymore.

After merging the new clean basic version we will:

- Add the deployment workflow for the svelte app (no mkdocs). Example here: https://github.com/josecelano/svelte-deploy-with-github-actions
- Setup the new MegaLinter with fixed warnings.

**Comment by grmbyrn** [comment]
Ok, so I will remove everything from this except what was in the SvelteKit folder and the READ.ME? What do you mean by add `site` to `.gitignore`? Is this in the repo?

**Comment by josecelano** [comment]
> Ok, so I will remove everything from this except what was in the SvelteKit folder and the READ.ME? What do you mean by add `site` to `.gitignore`? Is this in the repo?

I had a folder `site` in the root folder and I thought it was generated when you run `npm run build`. But the new version is using `/.svelte-kit` and it's already included in the `.gitignore` file so we do not include it in the repo.

**Comment by grmbyrn** [comment]
Okay, I have removed MegaLinter, mkdocs configuration, and both workflows. I also corrected the READ.ME header image's relative path to prevent the image from breaking.

**Review by josecelano — APPROVED** [review]

**Comment by josecelano** [comment]
ACK 86b7ff3120194c191b4e5d2a4cb1537dbc274a44

**Pull request merged**
